### ISSUE TITLE
Ceph health and status

### ISSUE THREAD

**Issue by arttor** [clyso/ceph-api#6]
Design grpc/rest api to report Ceph health and status. Please use:
- `ceph health detail --format=json` 
- `ceph status --format=json`
- please invesigate if there are any other useful sources. Ceph docs: https://docs.ceph.com/en/latest/man/8/ceph/

**Comment by arttor** [comment]
@jecluis do you have ideas what else can we use to obtain ceph health/status data or it is enough?

**Comment by shutstart** [comment]
Solved by #8
